(()=>{'use strict';
const state={viewer:null,buildings:[],entities:[],polys:[],terrainCache:new Map(),lastRoute:null};
const $=id=>document.getElementById(id),rad=d=>d*Math.PI/180,deg=r=>r*180/Math.PI,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function status(m){$('status').textContent=m;console.log('[ShadeRoute]',m)}
function parts(){const d=new Date(),p=n=>String(n).padStart(2,'0');return{date:`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`,time:`${p(d.getHours())}:${p(d.getMinutes())}`}}
function dateObj(){const p=parts();return new Date(`${$('dateInput').value||p.date}T${$('timeInput').value||p.time}:00`)}
function coord(s){const m=String(s).trim().match(/^\s*([0-9.\-]+)\s*,\s*([0-9.\-]+)\s*$/);if(!m)throw Error('座標は lat,lng 形式で入力してください');let a=+m[1],b=+m[2];return Math.abs(a)<=90?{lat:a,lng:b}:{lng:a,lat:b}}
function save(){['workerUrl','startInput','endInput','dateInput','timeInput','profile','cesiumToken','terrainAssetId','terrainMode','plateauUrl','sampleStep','maxSamples','tileWaitMs','shadeThreshold','heightMode','lineWidth','shadowGrid'].forEach(id=>localStorage.setItem('rollback.'+id,$(id).value));status('設定保存')}
function load(){const p=parts();$('dateInput').value=localStorage.getItem('rollback.dateInput')||p.date;$('timeInput').value=localStorage.getItem('rollback.timeInput')||p.time;['workerUrl','startInput','endInput','profile','cesiumToken','terrainAssetId','terrainMode','plateauUrl','sampleStep','maxSamples','tileWaitMs','shadeThreshold','heightMode','lineWidth','shadowGrid'].forEach(id=>{const v=localStorage.getItem('rollback.'+id);if(v!==null)$(id).value=v})}
async function init(){load();if($('cesiumToken').value)Cesium.Ion.defaultAccessToken=$('cesiumToken').value;state.viewer=new Cesium.Viewer('cesiumContainer',{animation:false,timeline:false,geocoder:false,sceneModePicker:false,baseLayerPicker:true,navigationHelpButton:false,shadows:true,terrainProvider:new Cesium.EllipsoidTerrainProvider()});state.viewer.scene.globe.enableLighting=false;state.viewer.scene.globe.depthTestAgainstTerrain=true;state.viewer.scene.shadowMap.enabled=true;visualShadow();state.viewer.camera.setView({destination:Cesium.Cartesian3.fromDegrees(139.76,35.68,3000)});events();if($('cesiumToken').value)applyTerrain().catch(e=>status('Terrain自動適用失敗: '+e.message));status('rollback版 起動完了')}
async function applyTerrain(){if($('terrainMode').value==='ellipsoid'){state.viewer.terrainProvider=new Cesium.EllipsoidTerrainProvider();return}if(!$('cesiumToken').value)throw Error('Cesium ion Tokenが必要です');Cesium.Ion.defaultAccessToken=$('cesiumToken').value;state.viewer.terrainProvider=await Cesium.CesiumTerrainProvider.fromIonAssetId(Number($('terrainAssetId').value||2767062),{requestVertexNormals:true});state.terrainCache.clear();status('Terrain適用完了')}
async function loadPlateau(){clearPlateau();const urls=$('plateauUrl').value.split(',').map(s=>s.trim()).filter(Boolean);status('PLATEAU読込中...');for(const u of urls){const ts=/^\d+$/.test(u)?await Cesium.Cesium3DTileset.fromIonAssetId(Number(u),{maximumScreenSpaceError:2}):await Cesium.Cesium3DTileset.fromUrl(u,{maximumScreenSpaceError:2,dynamicScreenSpaceError:true});ts.shadows=Cesium.ShadowMode.ENABLED;state.viewer.scene.primitives.add(ts);state.buildings.push(ts)}visualShadow();status('PLATEAU読込完了')}
function clearPlateau(){for(const b of state.buildings)try{state.viewer.scene.primitives.remove(b)}catch(e){}state.buildings=[]}
function visualShadow(){const v=state.viewer;if(!v)return;v.clock.currentTime=Cesium.JulianDate.fromDate(dateObj());v.shadows=true;v.scene.shadowMap.enabled=true;v.scene.globe.enableLighting=false;if(v.scene.shadowMap){v.scene.shadowMap.darkness=.25;v.scene.shadowMap.softShadows=false;v.scene.shadowMap.size=2048;v.scene.shadowMap.maximumDistance=3000}for(const b of state.buildings)b.shadows=Cesium.ShadowMode.ENABLED;status('見た目影ON')}
async function fetchRoute(){const w=$('workerUrl').value.trim().replace(/\/$/,'');if(!w)throw Error('Worker URLを入力してください');const a=coord($('startInput').value),b=coord($('endInput').value);const u=new URL(w+'/routes');u.searchParams.set('profile',$('profile').value);u.searchParams.set('start',`${a.lng},${a.lat}`);u.searchParams.set('end',`${b.lng},${b.lat}`);const r=await fetch(u),j=await r.json();if(!r.ok)throw Error('ルート取得失敗 '+JSON.stringify(j));const cs=j.features?.[0]?.geometry?.coordinates||j.geometry?.coordinates;if(!cs)throw Error('GeoJSONルートがありません');return cs.map(c=>({lng:c[0],lat:c[1]}))}
function dist(a,b){const p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*6371008.8*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function interp(a,b,f){return{lng:a.lng+(b.lng-a.lng)*f,lat:a.lat+(b.lat-a.lat)*f}}
function sample(route,step,max){const out=[route[0]];let next=step,done=0;for(let i=0;i<route.length-1&&out.length<max;i++){const a=route[i],b=route[i+1],L=dist(a,b);while(done+L>=next&&out.length<max){out.push(interp(a,b,(next-done)/L));next+=step}done+=L}return out}
function solar(date,lat,lng){const jd=date.getTime()/86400000+2440587.5,T=(jd-2451545)/36525;let L0=(280.46646+T*(36000.76983+T*.0003032))%360;if(L0<0)L0+=360;const M=357.52911+T*(35999.05029-.0001537*T),e=.016708634-T*(.000042037+.0000001267*T),C=Math.sin(rad(M))*(1.914602-T*(.004817+.000014*T))+Math.sin(rad(2*M))*(.019993-.000101*T)+Math.sin(rad(3*M))*.000289,omega=125.04-1934.136*T,lambda=L0+C-.00569-.00478*Math.sin(rad(omega)),eps=23.439291+.00256*Math.cos(rad(omega)),dec=deg(Math.asin(Math.sin(rad(eps))*Math.sin(rad(lambda)))),y=Math.tan(rad(eps)/2)**2,eq=4*deg(y*Math.sin(2*rad(L0))-2*e*Math.sin(rad(M))+4*e*y*Math.sin(rad(M))*Math.cos(2*rad(L0))-.5*y*y*Math.sin(4*rad(L0))-1.25*e*e*Math.sin(2*rad(M)));let tst=(date.getUTCHours()*60+date.getUTCMinutes()+eq+4*lng)%1440;if(tst<0)tst+=1440;let ha=tst/4-180,zen=Math.acos(clamp(Math.sin(rad(lat))*Math.sin(rad(dec))+Math.cos(rad(lat))*Math.cos(rad(dec))*Math.cos(rad(ha)),-1,1)),elev=90-deg(zen);let q=deg(Math.acos(clamp((Math.sin(rad(lat))*Math.cos(zen)-Math.sin(rad(dec)))/(Math.cos(rad(lat))*Math.sin(zen)),-1,1)));return{az:ha>0?(q+180)%360:(540-q)%360,elev}}
function dirSun(org,az,elev){const local=new Cesium.Cartesian3(Math.sin(rad(az))*Math.cos(rad(elev)),Math.cos(rad(az))*Math.cos(rad(elev)),Math.sin(rad(elev))),enu=Cesium.Transforms.eastNorthUpToFixedFrame(org);return Cesium.Cartesian3.normalize(Cesium.Matrix4.multiplyByPointAsVector(enu,local,new Cesium.Cartesian3()),new Cesium.Cartesian3())}
async function terrainH(p){const k=p.lng.toFixed(7)+','+p.lat.toFixed(7);if(state.terrainCache.has(k))return state.terrainCache.get(k);let h=0;try{h=(await Cesium.sampleTerrainMostDetailed(state.viewer.terrainProvider,[Cesium.Cartographic.fromDegrees(p.lng,p.lat)]))[0].height||0}catch(e){h=state.viewer.scene.globe.getHeight(Cesium.Cartographic.fromDegrees(p.lng,p.lat))||0}state.terrainCache.set(k,h);return h}
function clearEntities(){for(const e of state.entities)try{state.viewer.entities.remove(e)}catch(x){}state.entities=[];for(const e of state.polys)try{state.viewer.entities.remove(e)}catch(x){}state.polys=[]}
function add(e,poly=false){const x=state.viewer.entities.add(e);(poly?state.polys:state.entities).push(x);return x}
async function search(){clearEntities();visualShadow();const route=await fetchRoute();state.lastRoute=route;add({polyline:{positions:route.map(p=>Cesium.Cartesian3.fromDegrees(p.lng,p.lat)),width:3,clampToGround:true,material:Cesium.Color.WHITE.withAlpha(.5)}});await state.viewer.flyTo(state.viewer.entities,{duration:.5}).catch(()=>{});await new Promise(r=>setTimeout(r,+$('tileWaitMs').value));const samples=sample(route,+$('sampleStep').value,+$('maxSamples').value),date=dateObj(),thres=+$('shadeThreshold').value/100,heights=$('heightMode').value==='3'?[.2,1,1.7]:[1.7];let shade=0;for(const s of samples){let block=0,total=0;const sun=solar(date,s.lat,s.lng);for(const h of heights){const gh=await terrainH(s),org=Cesium.Cartesian3.fromDegrees(s.lng,s.lat,gh+h);let b=sun.elev<=0;if(!b){const hit=state.viewer.scene.pickFromRay(new Cesium.Ray(org,dirSun(org,sun.az,sun.elev)));b=!!(hit&&hit.position&&Cesium.Cartesian3.distance(org,hit.position)>.8)}if(b)block++;total++}s.shade=block/total>=thres;if(s.shade)shade++}for(let i=0;i<samples.length-1;i++){const a=samples[i],b=samples[i+1],col=a.shade?Cesium.Color.ROYALBLUE:Cesium.Color.RED;add({polyline:{positions:Cesium.Cartesian3.fromDegreesArray([a.lng,a.lat,b.lng,b.lat]),width:+$('lineWidth').value,clampToGround:true,material:col.withAlpha(.65)}})}status(`日陰解析完了\nサンプル: ${samples.length}\n日陰率: ${(shade/samples.length*100).toFixed(1)}%`)}
function ll(c){const g=Cesium.Cartographic.fromCartesian(c);return{lng:deg(g.longitude),lat:deg(g.latitude)}}
function toLocal(p,o){const R=6378137;return{x:rad(p.lng-o.lng)*R*Math.cos(rad(o.lat)),y:rad(p.lat-o.lat)*R}}
function toLL(x,y,o){const R=6378137;return{lng:o.lng+deg(x/(R*Math.cos(rad(o.lat)))),lat:o.lat+deg(y/R)}}
function rect(x0,y0,x1,y1,o){const a=toLL(x0,y0,o),b=toLL(x1,y0,o),c=toLL(x1,y1,o),d=toLL(x0,y1,o);return Cesium.Cartesian3.fromDegreesArray([a.lng,a.lat,b.lng,b.lat,c.lng,c.lat,d.lng,d.lat])}
async function groundShadow(){if(!state.lastRoute)throw Error('先に日陰ルート検索してください');const route=state.lastRoute,origin={lng:route.reduce((s,p)=>s+p.lng,0)/route.length,lat:route.reduce((s,p)=>s+p.lat,0)/route.length},loc=route.map(p=>toLocal(p,origin));let minX=Math.min(...loc.map(p=>p.x))-80,maxX=Math.max(...loc.map(p=>p.x))+80,minY=Math.min(...loc.map(p=>p.y))-80,maxY=Math.max(...loc.map(p=>p.y))+80;const step=Math.max(4,+$('shadowGrid').value||8),nx=Math.ceil((maxX-minX)/step),ny=Math.ceil((maxY-minY)/step),date=dateObj(),center=toLL((minX+maxX)/2,(minY+maxY)/2,origin),sun=solar(date,center.lat,center.lng);let count=0;for(let iy=0;iy<ny;iy++){for(let ix=0;ix<nx;ix++){const p=toLL(minX+(ix+.5)*step,minY+(iy+.5)*step,origin),gh=await terrainH(p),org=Cesium.Cartesian3.fromDegrees(p.lng,p.lat,gh+.2);let blocked=false;if(sun.elev<=0)blocked=true;else{const hit=state.viewer.scene.pickFromRay(new Cesium.Ray(org,dirSun(org,sun.az,sun.elev)));blocked=!!(hit&&hit.position&&Cesium.Cartesian3.distance(org,hit.position)>.8)}if(blocked){add({polygon:{hierarchy:rect(minX+ix*step,minY+iy*step,minX+(ix+1)*step,minY+(iy+1)*step,origin),material:Cesium.Color.BLACK.withAlpha(.42),outline:false,heightReference:Cesium.HeightReference.CLAMP_TO_GROUND,classificationType:Cesium.ClassificationType.BOTH}},true);count++}}if(iy%5===0)status(`地面影生成中 ${iy}/${ny}`)}status(`地面影ポリゴン生成完了: ${count} cells`)}
function events(){$('saveBtn').onclick=save;$('applyTerrainBtn').onclick=()=>applyTerrain().catch(e=>status('Terrainエラー: '+e.message));$('loadPlateauBtn').onclick=()=>loadPlateau().catch(e=>status('PLATEAUエラー: '+e.message));$('clearPlateauBtn').onclick=()=>{clearPlateau();status('建物クリア')};$('visualShadowBtn').onclick=visualShadow;$('searchBtn').onclick=()=>search().catch(e=>status('検索エラー: '+e.message));$('groundShadowBtn').onclick=()=>groundShadow().catch(e=>status('地面影エラー: '+e.message));$('clearBtn').onclick=()=>{clearEntities();status('表示クリア')}}
window.addEventListener('DOMContentLoaded',init);
})();