const PLATEAU_3DTILES_BASE='https://api.plateauview.mlit.go.jp/datacatalog/3dtiles';
const PLATEAU_PRESETS={
 '13101-lod1-latest':{area:'13101',lod:'lod1',texture:'',year:'latest'},
 '13-lod1-latest':{area:'13',lod:'lod1',texture:'',year:'latest'},
 'all-lod1-latest':{area:'all',lod:'lod1',texture:'',year:'latest'},
 '13101-maxlod2-latest':{area:'13101',lod:'maxlod2',texture:'',year:'latest'}
};
const state={viewer:null,buildings:[],entities:[],rayEntities:[],samples:[],terrainCache:new Map(),lastRoute:null,busy:false};
const $=id=>document.getElementById(id);
const rad=d=>d*Math.PI/180, deg=r=>r*180/Math.PI, clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function setStatus(m){$('appStatus').textContent=m; console.log('[ShadeRoute]',m)}
function toast(m){const t=$('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',3000);setStatus(m)}
function buildPlateauUrl(area,lod,texture,year){return `${PLATEAU_3DTILES_BASE}/${area||'13101'}-bldg-${lod||'lod1'}${texture?'-'+texture:''}-${year||'latest'}/tileset.json`}
function applyPlateauPreset(key){const p=PLATEAU_PRESETS[key]; if(p){$('cityCodeInput').value=p.area;$('lodInput').value=p.lod;$('textureInput').value=p.texture;$('yearInput').value=p.year} const u=buildPlateauUrl($('cityCodeInput').value.trim(),$('lodInput').value,$('textureInput').value,$('yearInput').value.trim()); $('plateauUrlInput').value=u; localStorage.setItem('shadeRoute.plateauUrl',u); $('plateauStatus').textContent='URL反映: '+u; return u}
function saveCommon(){['workerUrl','originInput','destinationInput','plateauUrlInput','cityCodeInput','yearInput'].forEach(id=>localStorage.setItem('shadeRoute.'+id,$(id).value)); ['plateauPreset','lodInput','textureInput'].forEach(id=>localStorage.setItem('shadeRoute.'+id,$(id).value))}
function localDateParts(){const d=new Date(); const pad=n=>String(n).padStart(2,'0'); return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`, time:`${pad(d.getHours())}:${pad(d.getMinutes())}`}}
function loadCommon(){const dt=localDateParts(); $('workerUrl').value=localStorage.getItem('shadeRoute.workerUrl')||''; $('originInput').value=localStorage.getItem('shadeRoute.originInput')||'35.681236,139.767125'; $('destinationInput').value=localStorage.getItem('shadeRoute.destinationInput')||'35.674510,139.758101'; $('cesiumToken').value=localStorage.getItem('shadeRoute.cesiumToken')||''; $('plateauPreset').value=localStorage.getItem('shadeRoute.plateauPreset')||'13101-lod1-latest'; $('cityCodeInput').value=localStorage.getItem('shadeRoute.cityCodeInput')||'13101'; $('lodInput').value=localStorage.getItem('shadeRoute.lodInput')||'lod1'; $('textureInput').value=localStorage.getItem('shadeRoute.textureInput')||''; $('yearInput').value=localStorage.getItem('shadeRoute.yearInput')||'latest'; $('plateauUrlInput').value=localStorage.getItem('shadeRoute.plateauUrl')||buildPlateauUrl('13101','lod1','','latest'); $('dateInput').value=localStorage.getItem('shadeRoute.dateInput')||dt.date; $('timeInput').value=localStorage.getItem('shadeRoute.timeInput')||dt.time}
function getAnalysisDate(){const d=$('dateInput').value || localDateParts().date; const t=$('timeInput').value || localDateParts().time; return new Date(`${d}T${t}:00`)}
async function init(){try{loadCommon(); if($('cesiumToken').value) Cesium.Ion.defaultAccessToken=$('cesiumToken').value; state.viewer=new Cesium.Viewer('cesiumContainer',{animation:true,timeline:true,geocoder:false,sceneModePicker:true,baseLayerPicker:true,shadows:false}); state.viewer.scene.globe.enableLighting=false; state.viewer.scene.shadowMap.enabled=false; state.viewer.scene.globe.depthTestAgainstTerrain=true; state.viewer.camera.setView({destination:Cesium.Cartesian3.fromDegrees(139.76,35.68,3000)}); setupEvents(); setupPick(); updateSunLabel(); if($('cesiumToken').value) applyTerrain().catch(e=>setStatus('Terrain自動適用失敗: '+e.message)); setStatus('準備完了。検索ボタンを押すと進捗がここに出ます。')}catch(e){console.error(e);setStatus('初期化エラー: '+e.message)}}
async function applyTerrain(){if($('terrainMode').value==='ellipsoid'){state.viewer.terrainProvider=new Cesium.EllipsoidTerrainProvider();$('terrainStatus').textContent='地形OFF';return} if(!$('cesiumToken').value.trim()) throw new Error('Cesium ion Tokenを入れてください'); Cesium.Ion.defaultAccessToken=$('cesiumToken').value.trim(); setStatus('Japan Regional Terrain適用中...'); state.viewer.terrainProvider=await Cesium.CesiumTerrainProvider.fromIonAssetId(Number($('terrainAssetId').value||2767062),{requestVertexNormals:true}); state.terrainCache.clear(); $('terrainStatus').textContent='Terrain適用完了'; setStatus('Terrain適用完了')}
async function loadPlateau(){clearPlateau(); saveCommon(); const srcs=$('plateauUrlInput').value.split(',').map(s=>s.trim()).filter(Boolean); if(!srcs.length) throw new Error('PLATEAU URLが空です'); setStatus('PLATEAU読込中...'); for(const src of srcs){let ts;if(/^\d+$/.test(src)) ts=await Cesium.Cesium3DTileset.fromIonAssetId(Number(src),{maximumScreenSpaceError:2}); else ts=await Cesium.Cesium3DTileset.fromUrl(src,{maximumScreenSpaceError:2,dynamicScreenSpaceError:true}); ts.shadows=Cesium.ShadowMode.ENABLED; state.viewer.scene.primitives.add(ts); state.buildings.push(ts)} $('plateauStatus').textContent='PLATEAU読込完了: '+srcs.join(', '); setStatus('PLATEAU読込完了')}
function clearPlateau(){for(const b of state.buildings){try{state.viewer.scene.primitives.remove(b)}catch(e){}} state.buildings=[]}
function parseCoord(s){let m=String(s).trim().match(/^\s*([0-9.\-]+)\s*,\s*([0-9.\-]+)\s*$/); if(!m) return null; let a=Number(m[1]),b=Number(m[2]); if(!Number.isFinite(a)||!Number.isFinite(b))return null; return Math.abs(a)<=90?{lat:a,lng:b}:{lng:a,lat:b}}
async function geocode(text){const c=parseCoord(text); if(c)return c; const w=$('workerUrl').value.replace(/\/$/,''); if(!w) throw new Error('住所/地名入力にはWorker URLが必要です'); const u=new URL(w+'/geocode'); u.searchParams.set('text',text.trim()); setStatus('ジオコード中: '+text); const r=await fetch(u); const j=await r.json().catch(()=>null); if(!r.ok) throw new Error('ジオコード失敗: '+JSON.stringify(j)); const f=j.features?.[0]||j; const coords=f.geometry?.coordinates || f.coordinates; if(!coords) throw new Error('ジオコード結果に座標がありません'); return {lng:coords[0],lat:coords[1]}}
async function fetchRoute(){const w=$('workerUrl').value.trim().replace(/\/$/,''); if(!w) throw new Error('Worker URLを入力してください'); const o=await geocode($('originInput').value), d=await geocode($('destinationInput').value); const u=new URL(w+'/routes'); u.searchParams.set('profile',$('travelMode').value); u.searchParams.set('start',`${o.lng},${o.lat}`); u.searchParams.set('end',`${d.lng},${d.lat}`); setStatus('ORSルート取得中...\n'+u.toString()); const r=await fetch(u); const j=await r.json().catch(()=>null); if(!r.ok) throw new Error('ルート取得失敗 HTTP '+r.status+' '+JSON.stringify(j)); const coords=j?.features?.[0]?.geometry?.coordinates || j?.geometry?.coordinates; if(!coords||coords.length<2) throw new Error('ルート座標が取れません。Worker /routes がGeoJSONを返しているか確認してください'); return coords.map(c=>({lng:c[0],lat:c[1]}))}
function dist(a,b){const R=6371008.8,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng); const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2; return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function interp(a,b,f){return{lng:a.lng+(b.lng-a.lng)*f,lat:a.lat+(b.lat-a.lat)*f}}
function sampleRoute(route,step,max){const out=[{...route[0],m:0}];let next=step,done=0;for(let i=0;i<route.length-1&&out.length<max;i++){const a=route[i],b=route[i+1],L=dist(a,b);while(done+L>=next&&out.length<max){out.push({...interp(a,b,(next-done)/L),m:next});next+=step}done+=L} if(out.length<max) out.push({...route[route.length-1],m:done}); return out}
function offset(p,e,n){const R=6378137;return{lng:p.lng+deg(e/(R*Math.cos(rad(p.lat)))),lat:p.lat+deg(n/R)}}
function tangent(samples,i){const a=samples[Math.max(0,i-1)],b=samples[Math.min(samples.length-1,i+1)],lat=rad(samples[i].lat);let e=rad(b.lng-a.lng)*Math.cos(lat)*6378137,n=rad(b.lat-a.lat)*6378137,L=Math.hypot(e,n)||1;return{e:e/L,n:n/L}}
function offsets(count,width){if(count<=1||width<=0)return[0];let a=[];for(let i=0;i<count;i++)a.push(-width+2*width*i/(count-1));return a}
async function terrainHeight(p){const key=p.lng.toFixed(7)+','+p.lat.toFixed(7); if(state.terrainCache.has(key))return state.terrainCache.get(key); let h=0; try{const c=(await Cesium.sampleTerrainMostDetailed(state.viewer.terrainProvider,[Cesium.Cartographic.fromDegrees(p.lng,p.lat)]))[0]; h=Number.isFinite(c.height)?c.height:0}catch(e){h=state.viewer.scene.globe.getHeight(Cesium.Cartographic.fromDegrees(p.lng,p.lat))||0} state.terrainCache.set(key,h); return h}
function sun(date,lat,lng){const jd=date.getTime()/86400000+2440587.5,T=(jd-2451545)/36525;let L0=(280.46646+T*(36000.76983+T*.0003032))%360;if(L0<0)L0+=360;const M=357.52911+T*(35999.05029-.0001537*T),e=.016708634-T*(.000042037+.0000001267*T),C=Math.sin(rad(M))*(1.914602-T*(.004817+.000014*T))+Math.sin(rad(2*M))*(.019993-.000101*T)+Math.sin(rad(3*M))*.000289,omega=125.04-1934.136*T,lambda=L0+C-.00569-.00478*Math.sin(rad(omega)),eps=23.439291+.00256*Math.cos(rad(omega));const dec=deg(Math.asin(Math.sin(rad(eps))*Math.sin(rad(lambda))));const y=Math.tan(rad(eps)/2)**2,eq=4*deg(y*Math.sin(2*rad(L0))-2*e*Math.sin(rad(M))+4*e*y*Math.sin(rad(M))*Math.cos(2*rad(L0))-.5*y*y*Math.sin(4*rad(L0))-1.25*e*e*Math.sin(2*rad(M)));let tst=(date.getUTCHours()*60+date.getUTCMinutes()+date.getUTCSeconds()/60+eq+4*lng)%1440;if(tst<0)tst+=1440;let ha=tst/4-180;const zen=Math.acos(clamp(Math.sin(rad(lat))*Math.sin(rad(dec))+Math.cos(rad(lat))*Math.cos(rad(dec))*Math.cos(rad(ha)),-1,1));let elev=90-deg(zen);let az;if(Math.abs(Math.sin(zen))<1e-6)az=180;else{const q=deg(Math.acos(clamp((Math.sin(rad(lat))*Math.cos(zen)-Math.sin(rad(dec)))/(Math.cos(rad(lat))*Math.sin(zen)),-1,1)));az=ha>0?(q+180)%360:(540-q)%360}return{az,elev}}
function dirToSun(origin,az,elev){const local=new Cesium.Cartesian3(Math.sin(rad(az))*Math.cos(rad(elev)),Math.cos(rad(az))*Math.cos(rad(elev)),Math.sin(rad(elev)));const enu=Cesium.Transforms.eastNorthUpToFixedFrame(origin);return Cesium.Cartesian3.normalize(Cesium.Matrix4.multiplyByPointAsVector(enu,local,new Cesium.Cartesian3()),new Cesium.Cartesian3())}
function clearEntities(){for(const e of [...state.entities,...state.rayEntities]){try{state.viewer.entities.remove(e)}catch(x){}}state.entities=[];state.rayEntities=[];state.samples=[];$('detail').style.display='none'}
function addEntity(e,ray=false){const x=state.viewer.entities.add(e);(ray?state.rayEntities:state.entities).push(x);return x}
async function analyze(route){clearEntities(); const date=getAnalysisDate(); state.viewer.clock.currentTime=Cesium.JulianDate.fromDate(date); const samples=sampleRoute(route,Number($('sampleStep').value),Number($('maxSamples').value)); const side=Number($('sideOffsetMeters').value), count=Number($('lateralMode').value), hs=$('heightMode').value==='3'?[.2,1,1.7]:[1.7], th=Number($('shadeThreshold').value)/100; setStatus(`解析準備中... サンプル ${samples.length}点`); addEntity({name:'ORSルート中心線',polyline:{positions:route.map(p=>Cesium.Cartesian3.fromDegrees(p.lng,p.lat)),width:3,clampToGround:true,material:Cesium.Color.WHITE.withAlpha(.5)}}); await state.viewer.flyTo(state.viewer.entities,{duration:.6}).catch(()=>{}); const wait=Number($('tileWaitMs').value); setStatus(`PLATEAUタイル読込待ち ${wait}ms...`); await new Promise(r=>setTimeout(r,wait)); const offs=offsets(count,side); for(let i=0;i<samples.length;i++){if(i%20===0)setStatus(`日陰解析中... ${i}/${samples.length}`);const s=samples[i],t=tangent(samples,i),le=-t.n,ln=t.e,sp=sun(date,s.lat,s.lng);s.sun=sp;s.rays=[];let blocked=0,total=0;for(const off of offs){const p=offset(s,le*off,ln*off),ter=await terrainHeight(p);for(const h of hs){let b=true,hitD=null;if(sp.elev>0){const org=Cesium.Cartesian3.fromDegrees(p.lng,p.lat,ter+h),dir=dirToSun(org,sp.az,sp.elev),hit=state.viewer.scene.pickFromRay(new Cesium.Ray(org,dir));b=!!(hit&&hit.position&&Cesium.Cartesian3.distance(org,hit.position)>.8);hitD=hit&&hit.position?Cesium.Cartesian3.distance(org,hit.position):null}s.rays.push({lng:p.lng,lat:p.lat,offset:off,height:h,terrain:ter,blocked:b,hitDistance:hitD});if(b)blocked++;total++}}s.score=total?blocked/total:0;s.shade=s.score>=th;s.blocked=blocked;s.total=total}state.samples=samples; for(let i=0;i<samples.length-1;i++){const a=samples[i],b=samples[i+1];addEntity({name:'road shade overlay',polyline:{positions:Cesium.Cartesian3.fromDegreesArray([a.lng,a.lat,b.lng,b.lat]),width:Number($('overlayWidth').value),clampToGround:true,material:(a.shade?Cesium.Color.ROYALBLUE:Cesium.Color.RED).withAlpha(.62)},properties:{sampleIndex:i}})} for(let i=0;i<samples.length;i++){let s=samples[i];addEntity({name:'sample',position:Cesium.Cartesian3.fromDegrees(s.lng,s.lat),point:{pixelSize:7,color:s.shade?Cesium.Color.DODGERBLUE:Cesium.Color.ORANGERED,outlineColor:Cesium.Color.WHITE,outlineWidth:1,heightReference:Cesium.HeightReference.CLAMP_TO_GROUND,disableDepthTestDistance:Number.POSITIVE_INFINITY},properties:{sampleIndex:i}})} const ratio=samples.filter(s=>s.shade).length/samples.length*100; $('results').innerHTML=`サンプル ${samples.length}点 / 日陰 ${ratio.toFixed(1)}%<br>日時: ${date.toLocaleString()}<br>太陽方向レイ: 判定点→太陽方向（C修正済み）<br>道路面オーバーレイ: ON（E修正済み）`; updateSunLabel(samples[0]?.sun); setStatus('日陰解析完了')}
function setupPick(){const h=new Cesium.ScreenSpaceEventHandler(state.viewer.scene.canvas);h.setInputAction(c=>{const p=state.viewer.scene.pick(c.position);if(!p||!p.id||!p.id.properties)return;const idx=p.id.properties.sampleIndex?.getValue?.();const s=state.samples[idx];if(!s)return;$('detailText').textContent=JSON.stringify({index:idx,lng:s.lng,lat:s.lat,shade:s.shade,score:(s.score*100).toFixed(1)+'%',blocked:s.blocked,total:s.total,sun:s.sun,rays:s.rays},null,2);$('detail').style.display='block'; for(const e of state.rayEntities)state.viewer.entities.remove(e);state.rayEntities=[]; const r=s.rays.find(x=>Math.abs(x.offset)<1e-6)||s.rays[0];const org=Cesium.Cartesian3.fromDegrees(r.lng,r.lat,r.terrain+r.height),dir=dirToSun(org,s.sun.az,s.sun.elev),end=Cesium.Cartesian3.add(org,Cesium.Cartesian3.multiplyByScalar(dir,350,new Cesium.Cartesian3()),new Cesium.Cartesian3());addEntity({name:'太陽方向レイ',polyline:{positions:[org,end],width:4,material:Cesium.Color.YELLOW}},true)},Cesium.ScreenSpaceEventType.LEFT_CLICK)}
function updateSunLabel(sp){const date=getAnalysisDate();$('clockLabel').textContent='解析日時: '+date.toLocaleString(); const c=parseCoord($('originInput').value)||{lat:35.681236,lng:139.767125}; const s=sp||sun(date,c.lat,c.lng); $('sunLabel').textContent=`太陽高度 ${s.elev.toFixed(1)}° / 方位 ${s.az.toFixed(1)}°`; state.viewer && (state.viewer.clock.currentTime=Cesium.JulianDate.fromDate(date));}
async function runSearch(){if(state.busy)return; state.busy=true; $('searchBtn').disabled=true; try{saveCommon();localStorage.setItem('shadeRoute.dateInput',$('dateInput').value);localStorage.setItem('shadeRoute.timeInput',$('timeInput').value);setStatus('検索開始...'); const route=await fetchRoute(); state.lastRoute=route; setStatus('ルート取得完了。日陰解析へ進みます...'); await analyze(route)}catch(e){console.error(e);toast('エラー: '+(e.message||e))}finally{state.busy=false;$('searchBtn').disabled=false}}
function setupEvents(){ $('togglePanel').onclick=()=>{document.querySelectorAll('.panel .card').forEach(c=>c.style.display=c.style.display==='none'?'block':'none')}; $('saveWorkerBtn').onclick=()=>{saveCommon();toast('保存しました')}; $('healthBtn').onclick=async()=>{try{setStatus('接続テスト中...');const r=await fetch($('workerUrl').value.replace(/\/$/,'')+'/health');$('healthText').textContent=await r.text();setStatus('接続テスト完了')}catch(e){$('healthText').textContent='失敗: '+e.message;setStatus('接続テスト失敗: '+e.message)}}; $('saveCesiumTokenBtn').onclick=()=>{localStorage.setItem('shadeRoute.cesiumToken',$('cesiumToken').value);Cesium.Ion.defaultAccessToken=$('cesiumToken').value;toast('Token保存')}; $('applyTerrainBtn').onclick=()=>applyTerrain().catch(e=>toast('Terrainエラー: '+e.message)); $('clearTerrainBtn').onclick=()=>{state.viewer.terrainProvider=new Cesium.EllipsoidTerrainProvider();toast('地形OFF')}; $('plateauPreset').onchange=()=>{applyPlateauPreset($('plateauPreset').value);saveCommon()}; ['cityCodeInput','lodInput','textureInput','yearInput'].forEach(id=>$(id).onchange=()=>{$('plateauPreset').value='custom';applyPlateauPreset('custom');saveCommon()}); document.querySelectorAll('button[data-area]').forEach(b=>b.onclick=()=>{const a=b.dataset.area;$('cityCodeInput').value=a;$('lodInput').value='lod1';$('plateauPreset').value=a==='13101'?'13101-lod1-latest':a==='13'?'13-lod1-latest':'all-lod1-latest';applyPlateauPreset('custom');saveCommon()}); $('applyPlateauUrlBtn').onclick=()=>{applyPlateauPreset('custom');saveCommon()}; $('loadPlateauBtn').onclick=()=>loadPlateau().catch(e=>toast('PLATEAUエラー: '+e.message)); $('clearPlateauBtn').onclick=()=>{clearPlateau();toast('建物クリア')}; $('useHereBtn').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{$('originInput').value=`${p.coords.latitude},${p.coords.longitude}`;updateSunLabel()},e=>toast('現在地取得失敗: '+e.message)); $('searchBtn').onclick=runSearch; $('recalcBtn').onclick=()=>{if(state.lastRoute) analyze(state.lastRoute).catch(e=>toast('再判定エラー: '+e.message)); else toast('先にルート検索してください')}; ['dateInput','timeInput','originInput'].forEach(id=>$(id).addEventListener('input',()=>{localStorage.setItem('shadeRoute.'+id,$(id).value);updateSunLabel()})); window.addEventListener('error',e=>setStatus('JSエラー: '+e.message)); window.addEventListener('unhandledrejection',e=>setStatus('Promiseエラー: '+(e.reason?.message||e.reason)));}
window.addEventListener('DOMContentLoaded',init);
