(() => {'use strict';
const PLATEAU_BASE='https://api.plateauview.mlit.go.jp/datacatalog/3dtiles';
const PRESETS={'13101-lod1-latest':{a:'13101',l:'lod1',t:'',y:'latest'},'13-lod1-latest':{a:'13',l:'lod1',t:'',y:'latest'},'all-lod1-latest':{a:'all',l:'lod1',t:'',y:'latest'},'13101-maxlod2-latest':{a:'13101',l:'maxlod2',t:'',y:'latest'}};
const state={viewer:null,buildings:[],entities:[],rays:[],samples:[],terrainCache:new Map(),lastRoute:null,busy:false,shadowPolys:[],routePositions:null,visualShadow:false};
const $=id=>document.getElementById(id), rad=d=>d*Math.PI/180, deg=r=>r*180/Math.PI, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), R=6378137;
function status(m){$('appStatus').textContent=m;console.log('[ShadeRoute]',m)} function sstatus(m){$('shadowPlusStatus').textContent=m;console.log('[Shadow+]',m)} function toast(m){const t=$('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',3000);status(m)}
function plateauUrl(a,l,t,y){return `${PLATEAU_BASE}/${a}-bldg-${l}${t?'-'+t:''}-${y}/tileset.json`} function applyPreset(k){const p=PRESETS[k];if(p){$('cityCodeInput').value=p.a;$('lodInput').value=p.l;$('textureInput').value=p.t;$('yearInput').value=p.y} const u=plateauUrl($('cityCodeInput').value,$('lodInput').value,$('textureInput').value,$('yearInput').value);$('plateauUrlInput').value=u;localStorage.setItem('sr.plateauUrl',u);$('plateauStatus').textContent=u}
function parts(){const d=new Date(),p=n=>String(n).padStart(2,'0');return{date:`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`,time:`${p(d.getHours())}:${p(d.getMinutes())}`}} function dateObj(){const p=parts();return new Date(`${$('dateInput').value||p.date}T${$('timeInput').value||p.time}:00`)}
function save(){['workerUrl','originInput','destinationInput','plateauUrlInput','cityCodeInput','yearInput','dateInput','timeInput'].forEach(id=>localStorage.setItem('sr.'+id,$(id).value));['plateauPreset','lodInput','textureInput'].forEach(id=>localStorage.setItem('sr.'+id,$(id).value));}
function load(){const p=parts();$('workerUrl').value=localStorage.getItem('sr.workerUrl')||'';$('originInput').value=localStorage.getItem('sr.originInput')||'35.681236,139.767125';$('destinationInput').value=localStorage.getItem('sr.destinationInput')||'35.674510,139.758101';$('cesiumToken').value=localStorage.getItem('sr.token')||'';$('plateauPreset').value=localStorage.getItem('sr.plateauPreset')||'13101-lod1-latest';$('cityCodeInput').value=localStorage.getItem('sr.cityCodeInput')||'13101';$('lodInput').value=localStorage.getItem('sr.lodInput')||'lod1';$('textureInput').value=localStorage.getItem('sr.textureInput')||'';$('yearInput').value=localStorage.getItem('sr.yearInput')||'latest';$('plateauUrlInput').value=localStorage.getItem('sr.plateauUrl')||plateauUrl('13101','lod1','','latest');$('dateInput').value=localStorage.getItem('sr.dateInput')||p.date;$('timeInput').value=localStorage.getItem('sr.timeInput')||p.time;}
async function init(){try{load();if($('cesiumToken').value)Cesium.Ion.defaultAccessToken=$('cesiumToken').value;state.viewer=new Cesium.Viewer('cesiumContainer',{animation:true,timeline:true,geocoder:false,sceneModePicker:true,baseLayerPicker:true,navigationHelpButton:false,shadows:false,terrainProvider:new Cesium.EllipsoidTerrainProvider()});state.viewer.scene.globe.enableLighting=false;state.viewer.scene.shadowMap.enabled=false;state.viewer.scene.globe.depthTestAgainstTerrain=true;state.viewer.camera.setView({destination:Cesium.Cartesian3.fromDegrees(139.76,35.68,3000)});events();pick();updateSun();if($('cesiumToken').value)applyTerrain().catch(e=>status('Terrain自動適用失敗:'+e.message));status('準備完了')}catch(e){status('初期化エラー:'+e.message)}}
async function applyTerrain(){if($('terrainMode').value==='ellipsoid'){state.viewer.terrainProvider=new Cesium.EllipsoidTerrainProvider();return}if(!$('cesiumToken').value)throw Error('Tokenを入力してください');Cesium.Ion.defaultAccessToken=$('cesiumToken').value;status('Terrain適用中...');state.viewer.terrainProvider=await Cesium.CesiumTerrainProvider.fromIonAssetId(Number($('terrainAssetId').value||2767062),{requestVertexNormals:true});state.terrainCache.clear();$('terrainStatus').textContent='Terrain適用完了';status('Terrain適用完了')}
async function loadPlateau(){clearPlateau();save();const srcs=$('plateauUrlInput').value.split(',').map(s=>s.trim()).filter(Boolean);status('PLATEAU読込中...');for(const src of srcs){const ts=/^\d+$/.test(src)?await Cesium.Cesium3DTileset.fromIonAssetId(Number(src),{maximumScreenSpaceError:2}):await Cesium.Cesium3DTileset.fromUrl(src,{maximumScreenSpaceError:2,dynamicScreenSpaceError:true});ts.shadows=state.visualShadow?Cesium.ShadowMode.ENABLED:Cesium.ShadowMode.DISABLED;state.viewer.scene.primitives.add(ts);state.buildings.push(ts)}$('plateauStatus').textContent='PLATEAU読込完了';status('PLATEAU読込完了')} function clearPlateau(){for(const b of state.buildings)try{state.viewer.scene.primitives.remove(b)}catch(e){}state.buildings=[]}
function coord(s){let m=String(s).trim().match(/^\s*([0-9.\-]+)\s*,\s*([0-9.\-]+)\s*$/);if(!m)return null;let a=+m[1],b=+m[2];return Math.abs(a)<=90?{lat:a,lng:b}:{lng:a,lat:b}} async function geocode(t){const c=coord(t);if(c)return c;const w=$('workerUrl').value.replace(/\/$/,'');const u=new URL(w+'/geocode');u.searchParams.set('text',t);const r=await fetch(u),j=await r.json();if(!r.ok)throw Error('ジオコード失敗:'+JSON.stringify(j));const cs=(j.features?.[0]||j).geometry?.coordinates;return{lng:cs[0],lat:cs[1]}}
async function fetchRoute(){const w=$('workerUrl').value.trim().replace(/\/$/,'');if(!w)throw Error('Worker URLを入力');const o=await geocode($('originInput').value),d=await geocode($('destinationInput').value);const u=new URL(w+'/routes');u.searchParams.set('profile',$('travelMode').value);u.searchParams.set('start',`${o.lng},${o.lat}`);u.searchParams.set('end',`${d.lng},${d.lat}`);status('ORSルート取得中...');const r=await fetch(u),j=await r.json();if(!r.ok)throw Error('ルート取得失敗 '+JSON.stringify(j));const cs=j.features?.[0]?.geometry?.coordinates||j.geometry?.coordinates;if(!cs)throw Error('GeoJSONルートがありません');return cs.map(c=>({lng:c[0],lat:c[1]}))}
function dist(a,b){const p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*6371008.8*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))} function interp(a,b,f){return{lng:a.lng+(b.lng-a.lng)*f,lat:a.lat+(b.lat-a.lat)*f}} function sample(route,step,max){const out=[{...route[0]}];let next=step,done=0;for(let i=0;i<route.length-1&&out.length<max;i++){let a=route[i],b=route[i+1],L=dist(a,b);while(done+L>=next&&out.length<max){out.push(interp(a,b,(next-done)/L));next+=step}done+=L}return out}
function solar(date,lat,lng){const jd=date.getTime()/86400000+2440587.5,T=(jd-2451545)/36525;let L0=(280.46646+T*(36000.76983+T*.0003032))%360;if(L0<0)L0+=360;const M=357.52911+T*(35999.05029-.0001537*T),e=.016708634-T*(.000042037+.0000001267*T),C=Math.sin(rad(M))*(1.914602-T*(.004817+.000014*T))+Math.sin(rad(2*M))*(.019993-.000101*T)+Math.sin(rad(3*M))*.000289,omega=125.04-1934.136*T,lambda=L0+C-.00569-.00478*Math.sin(rad(omega)),eps=23.439291+.00256*Math.cos(rad(omega)),dec=deg(Math.asin(Math.sin(rad(eps))*Math.sin(rad(lambda)))),y=Math.tan(rad(eps)/2)**2,eq=4*deg(y*Math.sin(2*rad(L0))-2*e*Math.sin(rad(M))+4*e*y*Math.sin(rad(M))*Math.cos(2*rad(L0))-.5*y*y*Math.sin(4*rad(L0))-1.25*e*e*Math.sin(2*rad(M)));let tst=(date.getUTCHours()*60+date.getUTCMinutes()+eq+4*lng)%1440;if(tst<0)tst+=1440;let ha=tst/4-180,zen=Math.acos(clamp(Math.sin(rad(lat))*Math.sin(rad(dec))+Math.cos(rad(lat))*Math.cos(rad(dec))*Math.cos(rad(ha)),-1,1)),elev=90-deg(zen);let q=deg(Math.acos(clamp((Math.sin(rad(lat))*Math.cos(zen)-Math.sin(rad(dec)))/(Math.cos(rad(lat))*Math.sin(zen)),-1,1)));return{az:ha>0?(q+180)%360:(540-q)%360,elev}}
function dirSun(org,az,elev){const local=new Cesium.Cartesian3(Math.sin(rad(az))*Math.cos(rad(elev)),Math.cos(rad(az))*Math.cos(rad(elev)),Math.sin(rad(elev))),enu=Cesium.Transforms.eastNorthUpToFixedFrame(org);return Cesium.Cartesian3.normalize(Cesium.Matrix4.multiplyByPointAsVector(enu,local,new Cesium.Cartesian3()),new Cesium.Cartesian3())}
async function th(p){const k=p.lng.toFixed(7)+','+p.lat.toFixed(7);if(state.terrainCache.has(k))return state.terrainCache.get(k);let h=0;try{h=(await Cesium.sampleTerrainMostDetailed(state.viewer.terrainProvider,[Cesium.Cartographic.fromDegrees(p.lng,p.lat)]))[0].height||0}catch(e){h=state.viewer.scene.globe.getHeight(Cesium.Cartographic.fromDegrees(p.lng,p.lat))||0}state.terrainCache.set(k,h);return h}
function clearEntities(){for(const e of [...state.entities,...state.rays])try{state.viewer.entities.remove(e)}catch(x){}state.entities=[];state.rays=[];state.samples=[]} function add(e,ray=false){const x=state.viewer.entities.add(e);(ray?state.rays:state.entities).push(x);return x}
async function analyze(route){clearEntities();const date=dateObj(),samples=sample(route,+$('sampleStep').value,+$('maxSamples').value);add({name:'ORSルート中心線',polyline:{positions:route.map(p=>Cesium.Cartesian3.fromDegrees(p.lng,p.lat)),width:3,clampToGround:true,material:Cesium.Color.WHITE.withAlpha(.5)}});state.routePositions=route.map(p=>Cesium.Cartesian3.fromDegrees(p.lng,p.lat));await state.viewer.flyTo(state.viewer.entities,{duration:.6}).catch(()=>{});await new Promise(r=>setTimeout(r,+$('tileWaitMs').value));const hts=$('heightMode').value==='3'?[.2,1,1.7]:[1.7],thres=+$('shadeThreshold').value/100;for(let i=0;i<samples.length;i++){const s=samples[i],sun=solar(date,s.lat,s.lng);s.sun=sun;s.rays=[];let bl=0,to=0;for(const h of hts){const gh=await th(s),org=Cesium.Cartesian3.fromDegrees(s.lng,s.lat,gh+h),hit=state.viewer.scene.pickFromRay(new Cesium.Ray(org,dirSun(org,sun.az,sun.elev)));const b=!!(hit&&hit.position&&Cesium.Cartesian3.distance(org,hit.position)>.8);if(b)bl++;to++;s.rays.push({h,blocked:b})}s.shade=bl/to>=thres;s.score=bl/to}state.samples=samples;for(let i=0;i<samples.length-1;i++){const a=samples[i],b=samples[i+1];add({name:'road shade overlay',polyline:{positions:Cesium.Cartesian3.fromDegreesArray([a.lng,a.lat,b.lng,b.lat]),width:+$('overlayWidth').value,clampToGround:true,material:(a.shade?Cesium.Color.ROYALBLUE:Cesium.Color.RED).withAlpha(.55)},properties:{sampleIndex:i}})}$('results').innerHTML=`サンプル ${samples.length} / 日陰 ${(samples.filter(s=>s.shade).length/samples.length*100).toFixed(1)}%`;updateSun();status('日陰解析完了')}
function updateSun(){const c=coord($('originInput').value)||{lat:35.681236,lng:139.767125},s=solar(dateObj(),c.lat,c.lng);$('clockLabel').textContent='解析日時: '+dateObj().toLocaleString();$('sunLabel').textContent=`太陽高度 ${s.elev.toFixed(1)}° / 方位 ${s.az.toFixed(1)}°`;if(state.viewer)state.viewer.clock.currentTime=Cesium.JulianDate.fromDate(dateObj())}
function visual(on){state.visualShadow=on;const v=state.viewer;v.clock.currentTime=Cesium.JulianDate.fromDate(dateObj());v.shadows=on;v.scene.globe.enableLighting=on;v.scene.shadowMap.enabled=on;v.scene.shadowMap.darkness=.55;v.scene.shadowMap.softShadows=true;v.scene.shadowMap.size=2048;for(const b of state.buildings)b.shadows=on?Cesium.ShadowMode.ENABLED:Cesium.ShadowMode.DISABLED;sstatus(on?'Cesium見た目影ON':'Cesium見た目影OFF')}
function ll(c){const g=Cesium.Cartographic.fromCartesian(c);return{lng:deg(g.longitude),lat:deg(g.latitude)}} function toLocal(p,o){return{x:rad(p.lng-o.lng)*R*Math.cos(rad(o.lat)),y:rad(p.lat-o.lat)*R}} function toLL(x,y,o){return{lng:o.lng+deg(x/(R*Math.cos(rad(o.lat)))),lat:o.lat+deg(y/R)}} function rect(x0,y0,x1,y1,o){let a=toLL(x0,y0,o),b=toLL(x1,y0,o),c=toLL(x1,y1,o),d=toLL(x0,y1,o);return Cesium.Cartesian3.fromDegreesArray([a.lng,a.lat,b.lng,b.lat,c.lng,c.lat,d.lng,d.lat])}
function clearPolys(){for(const e of state.shadowPolys)try{state.viewer.entities.remove(e)}catch(x){}state.shadowPolys=[];sstatus('ポリゴンクリア')} 
async function genPolys(){
  if(!state.routePositions) throw Error('先にルート検索してください');
  clearPolys(); visual(true);
  await new Promise(r=>setTimeout(r,+$('shadowPlusTileWait').value));
  const route=state.routePositions.map(ll);
  const o={lng:route.reduce((s,p)=>s+p.lng,0)/route.length,lat:route.reduce((s,p)=>s+p.lat,0)/route.length};
  const loc=route.map(p=>toLocal(p,o));
  const step=+$('shadowPlusStep').value;
  const buf=+$('shadowPlusBuffer').value;
  let minX=Math.min(...loc.map(p=>p.x))-buf,maxX=Math.max(...loc.map(p=>p.x))+buf,minY=Math.min(...loc.map(p=>p.y))-buf,maxY=Math.max(...loc.map(p=>p.y))+buf;
  let nx=Math.ceil((maxX-minX)/step),ny=Math.ceil((maxY-minY)/step);
  let useStep=step;
  if(nx*ny>3600){
    const step2=Math.ceil(step*Math.sqrt(nx*ny/3600));
    useStep=step2;
    nx=Math.ceil((maxX-minX)/useStep);
    ny=Math.ceil((maxY-minY)/useStep);
    sstatus(`格子間隔を${useStep}mに自動調整`);
  }
  const mat=Array.from({length:ny},()=>Array(nx).fill(false));
  const date=dateObj(),center=toLL((minX+maxX)/2,(minY+maxY)/2,o),sun=solar(date,center.lat,center.lng);
  let pts=[];
  for(let iy=0;iy<ny;iy++)for(let ix=0;ix<nx;ix++){let p=toLL(minX+(ix+.5)*useStep,minY+(iy+.5)*useStep,o);pts.push({ix,iy,...p})}
  for(let i=0;i<pts.length;i++){
    let p=pts[i],gh=await th(p),org=Cesium.Cartesian3.fromDegrees(p.lng,p.lat,gh+(+$('shadowPlusHeight').value)),hit=state.viewer.scene.pickFromRay(new Cesium.Ray(org,dirSun(org,sun.az,sun.elev)));
    mat[p.iy][p.ix]=!!(hit&&hit.position&&Cesium.Cartesian3.distance(org,hit.position)>.8);
    if(i%100===0)sstatus(`レイ判定中 ${i}/${pts.length}`)
  }
  let cnt=0,sh=0;
  for(let iy=0;iy<ny;iy++){
    let ix=0;
    while(ix<nx){
      if(!mat[iy][ix]){ix++;continue}
      let st=ix;
      while(ix<nx&&mat[iy][ix]){ix++;sh++}
      let en=ix;
      let ent=state.viewer.entities.add({name:'real building shadow polygon',polygon:{hierarchy:rect(minX+st*useStep,minY+iy*useStep,minX+en*useStep,minY+(iy+1)*useStep,o),material:Cesium.Color.BLACK.withAlpha(.42),outline:true,outlineColor:Cesium.Color.BLACK.withAlpha(.65),heightReference:Cesium.HeightReference.CLAMP_TO_GROUND,classificationType:Cesium.ClassificationType.BOTH,zIndex:10000}});
      state.shadowPolys.push(ent);cnt++
    }
  }
  sstatus(`完了: ${cnt} polygons / ${sh} shaded cells\nCesium見た目影ON + 地面影ポリゴンON`)
}
async function run(){if(state.busy)return;state.busy=true;try{save();status('検索開始');const r=await fetchRoute();state.lastRoute=r;await analyze(r)}catch(e){toast('エラー:'+e.message)}finally{state.busy=false}}
function pick(){const h=new Cesium.ScreenSpaceEventHandler(state.viewer.scene.canvas);h.setInputAction(c=>{const p=state.viewer.scene.pick(c.position);if(!p?.id?.properties)return;const idx=p.id.properties.sampleIndex?.getValue?.();const s=state.samples[idx];if(!s)return;$('detailText').textContent=JSON.stringify(s,null,2);$('detail').style.display='block'},Cesium.ScreenSpaceEventType.LEFT_CLICK)}
function events(){$('saveWorkerBtn').onclick=()=>{save();toast('保存')};$('healthBtn').onclick=async()=>{const r=await fetch($('workerUrl').value.replace(/\/$/,'')+'/health');$('healthText').textContent=await r.text()};$('saveCesiumTokenBtn').onclick=()=>{localStorage.setItem('sr.token',$('cesiumToken').value);Cesium.Ion.defaultAccessToken=$('cesiumToken').value;toast('Token保存')};$('applyTerrainBtn').onclick=()=>applyTerrain().catch(e=>toast(e.message));$('clearTerrainBtn').onclick=()=>{state.viewer.terrainProvider=new Cesium.EllipsoidTerrainProvider();toast('地形OFF')};$('plateauPreset').onchange=()=>applyPreset($('plateauPreset').value);$('applyPlateauUrlBtn').onclick=()=>applyPreset('custom');$('loadPlateauBtn').onclick=()=>loadPlateau().catch(e=>toast(e.message));$('clearPlateauBtn').onclick=()=>{clearPlateau();toast('建物クリア')};$('searchBtn').onclick=run;$('recalcBtn').onclick=()=>state.lastRoute?analyze(state.lastRoute):toast('先に検索');['dateInput','timeInput','originInput'].forEach(id=>$(id).oninput=updateSun);$('visualShadowOnBtn').onclick=()=>visual(true);$('visualShadowOffBtn').onclick=()=>visual(false);$('generateShadowPlusBtn').onclick=()=>genPolys().catch(e=>sstatus('生成エラー:'+e.message));$('clearShadowPlusBtn').onclick=clearPolys}
window.addEventListener('DOMContentLoaded',init);
})();