const ORS_BASE='https://api.openrouteservice.org';
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization'};
export default {async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{headers:CORS});const url=new URL(req.url);try{if(url.pathname==='/health')return json({ok:true,service:'ShadeRoute Worker v7'});if(url.pathname==='/routes')return routes(url,env);if(url.pathname==='/geocode')return geocode(url,env);return json({error:'not found'},404)}catch(e){return json({error:e.message,stack:e.stack},500)}}};
function key(env){const k=env.ORS_API_KEY||env.OPENROUTESERVICE_API_KEY||env.ORS_KEY;if(!k)throw new Error('ORS_API_KEY is not set');return k}
function json(x,status=200){return new Response(JSON.stringify(x,null,2),{status,headers:{...CORS,'Content-Type':'application/json;charset=utf-8'}})}
async function ors(path,params,env){const u=new URL(ORS_BASE+path);for(const [k,v] of Object.entries(params||{})){if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,v)}const r=await fetch(u,{headers:{Authorization:key(env)}});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body={raw:text}}if(!r.ok)throw new Error(`ORS ${path} ${r.status}: ${text.slice(0,400)}`);return body}
async function geocode(url,env){const text=(url.searchParams.get('text')||'').trim();const size=url.searchParams.get('size')||'8';const flat=url.searchParams.get('focus.lat')||url.searchParams.get('focus.point.lat');const flon=url.searchParams.get('focus.lon')||url.searchParams.get('focus.point.lon');if(!text)return json({features:[]});const variants=makeVariants(text);const features=[];for(const q of variants){for(const path of ['/geocode/autocomplete','/geocode/search']){try{const params={text:q,size,'boundary.country':'JP'};if(flat&&flon){params['focus.point.lat']=flat;params['focus.point.lon']=flon}const res=await ors(path,params,env);if(res.features)features.push(...res.features.map(f=>normalizeFeature(f,'ors'+path)))}catch(e){console.log('geocode try failed',q,path,e.message)}}if(features.length>=Number(size))break}return json({features:dedupe(features).slice(0,Number(size))})}
function makeVariants(t){const a=[t];if(!/日本|長野|東京|大阪|京都|県|都|府|市/.test(t))a.push(t+' 日本');a.push(t+' 長野県',t+' 長野県 佐久市',t+' 佐久市',t+' Japan');if(t.includes('市役所'))a.push(t.replace('市役所',' 市役所'));return [...new Set(a.map(s=>s.trim()).filter(Boolean))]}
function normalizeFeature(f,source){const p=f.properties||{},c=f.geometry?.coordinates||[];return {type:'Feature',geometry:{type:'Point',coordinates:c},properties:{label:p.label||p.name||p.locality||'',name:p.name||p.label||'',address:[p.region,p.locality,p.street,p.housenumber].filter(Boolean).join(' '),region:p.region||'',county:p.county||'',source}}}
function dedupe(fs){const seen=new Set();return fs.filter(f=>{const c=f.geometry.coordinates||[];const label=f.properties.label||'';const k=label+'|'+Number(c[0]).toFixed(5)+'|'+Number(c[1]).toFixed(5);if(seen.has(k)||!c.length)return false;seen.add(k);return true})}
async function routes(url,env){const profile=url.searchParams.get('profile')||'foot-walking';const start=url.searchParams.get('start');const end=url.searchParams.get('end');if(!start||!end)throw new Error('start and end are required');const u=`${ORS_BASE}/v2/directions/${profile}/geojson`;const body={coordinates:[start.split(',').map(Number),end.split(',').map(Number)]};const r=await fetch(u,{method:'POST',headers:{Authorization:key(env),'Content-Type':'application/json'},body:JSON.stringify(body)});const text=await r.text();if(!r.ok)throw new Error(`ORS routes ${r.status}: ${text.slice(0,400)}`);return new Response(text,{headers:{...CORS,'Content-Type':'application/json;charset=utf-8'}})}
